owner: 0ceanSlim
repo: upptime
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from my [GitHub repository](https://github.com/oceanslim/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

# Each site/url you want to monitor:
sites:
  - name: Happy Tavern
    url: https://happytavern.co
    description: Main Website

  - name: Jellyfin
    url: https://jellyfin.happytavern.co
    description: Media Server

  - name: Jellyseer
    url: https://discover.happytavern.co
    description: Media Requests

  - name: Immich
    url: https://immich.happytavern.co
    description: Photo Management

  - name: AudioBookshelf
    url: https://books.happytavern.co
    description: Audiobook Server

  - name: Mempool
    url: https://mempool.happytavern.co
    description: Block Explorer

  - name: Ord Server
    url: https://ord.happytavern.co
    description: Bitcoin Ordinals

  - name: DWM Game App
    url: https://dwm.happytavern.co
    description: DWM Game App

  - name: Nostr Hero
    url: https://hero.happytavern.co
    description: Nostr Client

  - name: Wheat
    url: https://wheat.happytavern.co
    description: Nostr Relay

  - name: Link
    url: https://link.happytavern.co
    description: Experimental nostr client

# You can add more services here following the above pattern.
